<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\alterEgoEditorIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\alterEgoEditorIcon.ico" />
    <Resource Include="Resources\Icons\EditorLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FileHandler\" />
    <Folder Include="UIHandler\" />
    <Folder Include="ViewModel\" />
    <Folder Include="Resources\Images\" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Resources\SplashScreen\SplashScreen.png" />
  </ItemGroup>

</Project>
