<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\alterEgoEditorIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Test.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Test.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\alterEgoEditorIcon.ico" />
    <Resource Include="Resources\Icons\EditorLogo.png" />
    <SplashScreen Include="Resources\SplashScreen\SplashScreen.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Engine\Engine.csproj" />
  </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\StartupView.xaml.cs">
            <DependentUpon>StartupView.xaml</DependentUpon>
        </Compile>
        <Compile Update="Views\CreateProjectWindow.xaml.cs">
            <DependentUpon>CreateProjectWindow.xaml</DependentUpon>
        </Compile>
        <Compile Update="Views\EditorView.xaml.cs">
            <DependentUpon>EditorView.xaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Page Update="Views\StartupView.xaml">
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\CreateProjectWindow.xaml">
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\EditorView.xaml">
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

</Project>
